### ISSUE TITLE
Agroforestry Table's Crafting Recipe

### ISSUE THREAD

**Issue by Rayawa** [Featurehouse/sweet_potato-issueTracker#22]
Related to #13, recipe can not unlock.

Maby we can add a GUI like Crafting Table to Agroforestry Table.

For example using a book in the GUI an I can "craft" in the Agroforestry Table just like the Crafting Table.

**Comment by teddyxlandlee** [comment]
Recipes for Agroforestry Table will be able to be unlocked in 1.1.1.  
We'll try to add the GUI at the same version.
