### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by Rayawa** [Featurehouse/sweet_potato-issueTracker#23]
There are rare sound added in this Mod, I'd like more sounds.

For example: Magic Cube activate/deactivate, Grinder grind..........

The sound "Crop Upgraded" in now a bit weird, the sound is like metal but crops can;t sound like that.

**Comment by teddyxlandlee** [comment]
We'll try to add sounds this (1.1.1) or next version.

**Comment by Rayawa** [comment]
Added in version 1.1.1
